// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Port } from "./Port";

export type Container = { name: string, imagePullPolicy: string | null, resources: any, terminationMessagePath: string | null, terminationMessagePolicy: string | null, volumeMounts: any[], image: string, ports: Array<Port>, templateId: string, };
