// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotations } from "./Annotations";
import type { Labels } from "./Labels";

export type Metadata = { fields: (any | undefined)[], namespace: string, name: string, labels: Labels, annotations: Annotations, resourceVersion: string | null, };
