// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Labels } from "./Labels";

export type Metadata = { name: string, labels: Labels, };
