// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "./Metadata";
import type { Spec } from "./Spec";

export type PodTemplate = { id: string | null, apiVersion: string, kind: string, metadata: Metadata, spec: Spec, };
