// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Container } from "./Container";

export type Spec = { affinity: any, containers: Array<Container>, dnsPolicy: string | null, enableServiceLinks: boolean | null, nodeName: string | null, preemptionPolicy: string | null, priority: bigint | null, restartPolicy: string | null, schedulerName: string | null, securityContext: any, serviceAccount: string | null, serviceAccountName: string | null, terminationGracePeriodSeconds: bigint | null, tolerations: any[], volumes: any[], imagePullSecrets: any[], initContainers: any[], };
