name: Build and Release Rancher Dashboard - Rancher Desktop Embed

on:
  push:
    tags:
        - 'desktop-v*'

env:
  OUTPUT_DIR: dist
  RELEASE_DIR: release
  ARTIFACT_NAME: rancher-dashboard-desktop-embed
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    
    - name: Install & Build
      run: |
        mkdir ${{ env.RELEASE_DIR }}
        yarn install --frozen-lockfile
        NUXT_ENV_commit=${GITHUB_SHA} NUXT_ENV_version=${GITHUB_REF_NAME} OUTPUT_DIR=${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }} ROUTER_BASE='/dashboard' RANCHER_ENV=desktop yarn run build --spa
        tar -czf ${{ env.RELEASE_DIR }}/${{ env.ARTIFACT_NAME }}.tar.gz -C ${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }} .
        sha512sum ${{ env.RELEASE_DIR }}/${{ env.ARTIFACT_NAME }}.tar.gz > ${{ env.RELEASE_DIR }}/${{ env.ARTIFACT_NAME }}.tar.gz.sha512sum

    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        path: ${{ env.RELEASE_DIR}}/${{ env.ARTIFACT_NAME }}*
        name: ${{ env.ARTIFACT_NAME }}
        if-no-files-found: error

    - name: Upload Assets
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.RELEASE_DIR }}/*
        tag: ${{ github.ref }}
        file_glob: true
